version: 2
updates:
  # Enable version updates for npm (Docusaurus documentation)
  - package-ecosystem: "npm"
    directory: "/promptpack-docs"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "altairalabs"
    labels:
      - "dependencies"
      - "automated"
    commit-message:
      prefix: "chore(deps):"
      include: "scope"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 3
    reviewers:
      - "altairalabs"
    labels:
      - "dependencies"
      - "github-actions"
      - "automated"
    commit-message:
      prefix: "chore(actions):"
      include: "scope"