blank_issues_enabled: false
contact_links:
  - name: 🤔 Questions and Help
    url: https://github.com/altairalabs/promptpack-spec/discussions
    about: Ask questions and get help from the community
  - name: 💬 General Discussion
    url: https://github.com/altairalabs/promptpack-spec/discussions
    about: Discuss ideas, feedback, and general topics about PromptPack
  - name: 🔒 Security Issues
    url: https://github.com/altairalabs/promptpack-spec/security/advisories/new
    about: Report security vulnerabilities privately