#!/usr/bin/env node

/**
 * Sync RFCs from /rfcs/ to /promptpack-docs/docs/rfcs/
 * Adds Docusaurus frontmatter to each RFC file
 * 
 * Automatically extracts RFC metadata from the file content:
 * - RFC number from filename
 * - Title from the first heading (# RFC XXXX: Title)
 * - Description from the Summary section
 */

const fs = require('fs');
const path = require('path');

// Paths
const RFC_SOURCE_DIR = path.join(__dirname, '../../rfcs');
const RFC_DEST_DIR = path.join(__dirname, '../docs/rfcs');
const RFC_INDEX_PATH = path.join(__dirname, '../docs/rfcs/index.md');

// Where RFC feedback goes. Discussions has an "RFC Comments" category; before
// this, nothing pointed at it and it sat empty while people improvised in
// Issues instead.
const REPO_URL = 'https://github.com/AltairaLabs/promptpack-spec';
const DISCUSSION_CATEGORY = 'rfc-comments';

// Hand-maintained mapping of RFC number → spec version that implemented it.
// Update when a new RFC ships in a spec release.
const RFC_SPEC_VERSION = {
  1: 'v1.0',
  2: 'v1.0',
  3: 'v1.0',
  4: 'v1.1',
  5: 'v1.3',
  6: 'v1.2',
  7: 'v1.3',
  8: 'v1.3.1',
  9: 'v1.4',
  10: 'v1.5.0',
  11: 'v1.4.1',
  12: 'v1.5.1',
  13: 'v1.6.0',
  14: 'v1.7.0',
  15: 'v1.7.0',
};

/**
 * Extract RFC metadata from file content
 */
function extractMetadata(filename, content) {
  // Extract RFC number from filename (e.g., "0001-core-schema.md" -> 1)
  const rfcNumberMatch = filename.match(/^(\d{4})-/);
  const position = rfcNumberMatch ? parseInt(rfcNumberMatch[1], 10) : 999;
  
  // Extract title from first heading (# RFC XXXX: Title)
  const titleMatch = content.match(/^#\s+(RFC\s+\d{4}:\s+.*?)$/m);
  const titleFromHeading = titleMatch ? titleMatch[1] : null;
  
  // Fallback: extract from filename if heading not found
  const titleFromFilename = filename
    .replace(/\.md$/, '')
    .replace(/^(\d{4})-/, 'RFC-$1: ')
    .split('-')
    .map(word => word.charAt(0).toUpperCase() + word.slice(1))
    .join(' ');
  
  const title = titleFromHeading || titleFromFilename;
  
  // Extract description from Summary section
  let description = '';
  const summaryMatch = content.match(/##\s+Summary\s*\n\s*\n(.*?)(?=\n\n##|\n##|$)/s);
  if (summaryMatch) {
    // Take first sentence or first line of summary
    description = summaryMatch[1]
      .trim()
      .split(/\.\s+|\n/)[0]
      .replace(/\[([^\]]+)\]\([^\)]+\)/g, '$1') // Remove markdown links
      .replace(/[*_`]/g, '') // Remove markdown formatting
      .trim();
    
    // Truncate if too long
    if (description.length > 120) {
      description = description.substring(0, 117) + '...';
    }
  }
  
  // Fallback description
  if (!description) {
    description = `RFC ${String(position).padStart(4, '0')} specification document`;
  }
  
  // Extract status from metadata line (e.g., "- **Status:** Implemented")
  const statusMatch = content.match(/[-*]\s*\*\*Status[:]?\*\*[:\s]*(.*)/i);
  const status = statusMatch ? statusMatch[1].trim() : 'Draft';

  // Extract Created and Updated dates from metadata block
  const createdMatch = content.match(/[-*]\s*\*\*Created[:]?\*\*[:\s]*(\d{4}-\d{2}-\d{2})/i);
  const updatedMatch = content.match(/[-*]\s*\*\*Updated[:]?\*\*[:\s]*(\d{4}-\d{2}-\d{2})/i);
  const created = createdMatch ? createdMatch[1] : '—';
  const updated = updatedMatch ? updatedMatch[1] : '—';

  // An RFC may name its own discussion thread. Once one exists, everyone should
  // land in it rather than opening a second.
  const discussionMatch = content.match(/[-*]\s*\*\*Discussion[:]?\*\*[:\s]*(\S+)/i);
  const discussion = discussionMatch ? discussionMatch[1].trim() : null;

  return { position, title, description, status, created, updated, discussion, hasTitleHeading: Boolean(titleFromHeading) };
}

/**
 * Generate Docusaurus frontmatter for an RFC
 */
function generateFrontmatter(metadata) {
  // Starlight frontmatter. There is deliberately no `slug:` — the URL comes
  // from the filename now (see rfcDestName), because Starlight's `slug` is
  // absolute from the collection root while Docusaurus's was relative to the
  // file. Keeping it would have moved every RFC from /docs/rfcs/core-schema to
  // /core-schema, which are public specification URLs.
  //
  // `sidebar.order` replaces `sidebar_position`; the RFC sidebar category is
  // autogenerated, so the order still has to come from the page.
  // Both values are YAML scalars built from arbitrary RFC prose, so they are
  // emitted as JSON strings: YAML 1.2's double-quoted style is JSON-compatible,
  // and JSON.stringify escapes the quotes and backslashes that would otherwise
  // end the scalar early.
  //
  // description used to be emitted bare. That works right up until a Summary's
  // first sentence contains ": ", at which point YAML reads the line as a
  // nested mapping and the docs build fails with "bad indentation of a mapping
  // entry" — pointing at the generated file, which is gitignored, rather than
  // at the RFC that caused it. A colon in a summary is ordinary prose, so the
  // generator has to survive it.
  return `---
title: ${JSON.stringify(metadata.title)}
description: ${JSON.stringify(metadata.description)}
sidebar:
  order: ${metadata.position}
---

`;
}

/**
 * Destination filename: the RFC number prefix is dropped so the path itself
 * produces the URL Docusaurus produced via `slug:` — /docs/rfcs/core-schema.
 * The number survives as sidebar.order, which is what it was for.
 */
function rfcDestName(filename) {
  return filename.replace(/^\d{4}-/, '');
}

/**
 * A line telling a reader where to comment.
 *
 * The published RFC used to say it was open for comment while offering nowhere
 * to leave one: the PR that carried it is merged and closed, and the page is
 * static. If the RFC names a thread, link it; otherwise link a pre-filled new
 * discussion in the RFC Comments category, so the first commenter does not have
 * to work out where it belongs.
 */
function discussionBanner(metadata) {
  const all = `${REPO_URL}/discussions/categories/${DISCUSSION_CATEGORY}`;
  const link = metadata.discussion
    ? `[join the discussion](${metadata.discussion})`
    : `[start a discussion](${REPO_URL}/discussions/new?category=${DISCUSSION_CATEGORY}&title=${encodeURIComponent(metadata.title)})`;
  return `> **Comments on this RFC:** ${link} — or browse [all RFC discussions](${all}).\n\n`;
}

/**
 * Remove the source file's own `# RFC NNNN: Title` heading.
 *
 * The heading has to stay in /rfcs/*.md — those are read directly on GitHub,
 * where nothing else supplies a title. On the docs site Starlight renders the
 * frontmatter `title` as the page <h1>, so carrying the heading through gave
 * every RFC page two <h1> elements with identical text. Docusaurus did not
 * render the frontmatter title as a heading, so this only became wrong at the
 * Astro migration.
 *
 * Anchored at the start of the string, not /m: only a heading that is the very
 * first thing in the file is removed, never a `# RFC ...` line occurring later.
 */
function stripTitleHeading(content) {
  return content.replace(/^#\s+RFC\s+\d{4}:.*\r?\n(?:\r?\n)*/, '');
}

/**
 * Sync a single RFC file
 */
function syncRFC(filename) {
  const sourcePath = path.join(RFC_SOURCE_DIR, filename);
  const destPath = path.join(RFC_DEST_DIR, rfcDestName(filename));
  
  // Skip if not an RFC file or if it's the template
  const rfcPattern = /^\d{4}-.*\.md$/;
  if (!rfcPattern.test(filename) || filename === '0000-template.md') {
    console.log(`⏭️  Skipping: ${filename}`);
    return;
  }
  
  try {
    // Read source file
    const content = fs.readFileSync(sourcePath, 'utf8');
    
    // Extract metadata from content
    const metadata = extractMetadata(filename, content);
    
    // Generate frontmatter
    const frontmatter = generateFrontmatter(metadata);
    
    // Combine frontmatter + content. The source heading is dropped only when it
    // is what produced the frontmatter title, so the filename-fallback path
    // cannot leave a page with no title at all.
    const body = metadata.hasTitleHeading ? stripTitleHeading(content) : content;
    const outputContent = frontmatter + discussionBanner(metadata) + body;
    
    // Write to destination
    fs.writeFileSync(destPath, outputContent, 'utf8');
    console.log(`✅ Synced: ${filename} (position: ${metadata.position})`);
    console.log(`   Title: ${metadata.title}`);
    console.log(`   Description: ${metadata.description}\n`);
  } catch (error) {
    console.error(`❌ Error syncing ${filename}:`, error.message);
    process.exit(1);
  }
}

/**
 * Normalise status text for the generated tables.
 *
 * Deliberately plain words: the AltairaLabs voice rules forbid emoji outright,
 * and this map previously emitted a rocket into every "Implemented" row of the
 * RFC index — the canonical anti-example of the house style.
 */
const STATUS_LABEL = {
  'draft': 'Draft',
  'review': 'Review',
  'accepted': 'Accepted',
  'implemented': 'Implemented',
  'rejected': 'Rejected',
  'deferred': 'Deferred',
};

function formatStatus(status) {
  return STATUS_LABEL[status.toLowerCase()] || status;
}

/**
 * Update the RFC index table in rfc-index.md
 */
function updateRfcIndex(rfcEntries) {
  if (!fs.existsSync(RFC_INDEX_PATH)) {
    console.log('⚠️  rfcs/index.md not found, skipping index update');
    return;
  }

  const indexContent = fs.readFileSync(RFC_INDEX_PATH, 'utf8');

  // Build the table
  const header = '| # | Title | Status | Spec | Created | Updated |\n|---|-------|--------|------|---------|---------|';
  const sorted = rfcEntries.sort((a, b) => a.position - b.position);
  const rows = sorted.map(e => {
    const slug = e.filename.replace(/^\d{4}-/, '').replace(/\.md$/, '');
    const rfcNum = String(e.position).padStart(4, '0');
    const shortTitle = e.title.replace(/^RFC\s+\d{4}:\s*/, '');
    const spec = RFC_SPEC_VERSION[e.position] || '—';
    return `| [RFC-${rfcNum}](/docs/rfcs/${slug}) | ${shortTitle} | ${formatStatus(e.status)} | ${spec} | ${e.created} | ${e.updated} |`;
  });

  const table = [header, ...rows].join('\n');
  let newContent = indexContent.replace(
    /<!-- RFC_TABLE_START -->[\s\S]*?<!-- RFC_TABLE_END -->/,
    `<!-- RFC_TABLE_START -->\n${table}\n<!-- RFC_TABLE_END -->`
  );

  // Also refresh the At-a-Glance counts
  const total = sorted.length;
  const implemented = sorted.filter(e => /implemented/i.test(e.status)).length;
  const draft = sorted.filter(e => /draft/i.test(e.status)).length;
  const review = sorted.filter(e => /review/i.test(e.status)).length;
  const rejected = sorted.filter(e => /rejected/i.test(e.status)).length;
  const countsBlock =
    `<!-- RFC_COUNTS_START -->\n` +
    `| | Count |\n|---|---|\n` +
    `| Total RFCs | ${total} |\n` +
    `| Implemented | ${implemented} |\n` +
    `| Draft | ${draft} |\n` +
    `| In Review | ${review} |\n` +
    `| Rejected | ${rejected} |\n` +
    `<!-- RFC_COUNTS_END -->`;
  newContent = newContent.replace(
    /<!-- RFC_COUNTS_START -->[\s\S]*?<!-- RFC_COUNTS_END -->/,
    countsBlock
  );

  fs.writeFileSync(RFC_INDEX_PATH, newContent, 'utf8');
  console.log(`📋 Updated RFC index table with ${rfcEntries.length} entries\n`);
}

/**
 * Main sync function
 */
function syncAllRFCs() {
  console.log('🔄 Syncing RFCs from /rfcs/ to /promptpack-docs/docs/rfcs/\n');

  // Ensure destination directory exists
  if (!fs.existsSync(RFC_DEST_DIR)) {
    fs.mkdirSync(RFC_DEST_DIR, { recursive: true });
    console.log(`📁 Created directory: ${RFC_DEST_DIR}\n`);
  }

  // Read all files from source directory
  const files = fs.readdirSync(RFC_SOURCE_DIR);

  // Sync each RFC and collect metadata for index
  const rfcPattern = /^\d{4}-.*\.md$/;
  const rfcEntries = [];
  let syncedCount = 0;

  for (const filename of files) {
    if (rfcPattern.test(filename) && filename !== '0000-template.md') {
      syncRFC(filename);

      // Read source content to collect metadata for the index
      const content = fs.readFileSync(path.join(RFC_SOURCE_DIR, filename), 'utf8');
      const metadata = extractMetadata(filename, content);
      rfcEntries.push({ filename, ...metadata });

      syncedCount++;
    }
  }

  // Update the RFC index table
  updateRfcIndex(rfcEntries);

  console.log(`✨ Successfully synced ${syncedCount} RFC(s)`);
}

// Run if called directly
if (require.main === module) {
  syncAllRFCs();
}

module.exports = { syncAllRFCs };
